#if !canImport(ObjectiveC)
import XCTest

extension JWTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JWTTests = [
        ("testExpirationDecoding", testExpirationDecoding),
        ("testExpirationEncoding", testExpirationEncoding),
        ("testExpired", testExpired),
        ("testParse", testParse),
        ("testRSA", testRSA),
        ("testSigners", testSigners),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JWTTests.__allTests__JWTTests),
    ]
}
#endif
